[package]
name = "cartconf"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cartconf"
crate-type = ["cdylib"]

[dependencies]
regex = "1.7"
tempfile = "3.23.0"
hashbrown = "0.16.1"
pyo3 = { version = "0.28.3", features = ["hashbrown"] }
