[package]
name = "cartconf"
version = "0.1.0"
edition = "2024"
description = "Cartesian config varianter plugin for the Avocado framework"
license = "GPL-2.0"
repository = "https://github.com/avocado-framework/cartconf"
homepage = "https://github.com/avocado-framework/cartconf"
documentation = "https://github.com/avocado-framework/cartconf"
authors = ["CartConf contributors"]
readme = "README.rst"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "cartconf"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[[bin]]
name = "cartconf"
path = "src/main.rs"

[dependencies]
regex = "1.7"
tempfile = "3.23.0"
hashbrown = "0.16.1"
pyo3 = { version = "0.28.3", features = ["hashbrown"] }
clap = { version = "4.5", features = ["derive"] }
