---
name: CartConf CI

on: [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run isolation tests
        run: python3 -m unittest tests/test_*

      - name: Install requirements
        run: |
          pip install -r requirements_pip.txt
          pip install -e .

      - name: Run integration tests
        run: |
          ./parse.py -c tests/example.cfg "aaa=bbb" "c=d" "only a" "only 1"
          avocado variants -C tests/example.cfg -o aaa=bbb c=d --only a 1
